apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-go-rhtap-three-component-scenarios-yuah
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-mzks-tenant/mc-three-scenarios/devfile-go-rhtap-three-component-scenarios-yuah@sha256:2b72abb2ec508ff57ead22b08e8e107cbd230a6b2f5b29b2c9b258cc5f1bd877
        name: my-go
        resources: {}
status: {}
